#!/usr/bin/env python3
"""Remove CLI wrapper installed by install_cli_wrapper.py.

Usage:
  remove_cli_wrapper.py --cli gh
  remove_cli_wrapper.py --cli gh --dir ~/.local/bin
  remove_cli_wrapper.py --cli gh --dry-run
"""

import argparse
from pathlib import Path

DEFAULT_DIR = Path.home() / ".local" / "bin"


def is_our_wrapper(path: Path) -> bool:
    """Check if file is a wrapper generated by us."""
    if not path.exists():
        return False
    try:
        content = path.read_text()
        return "Generated by ai-hooks-integration" in content
    except (PermissionError, OSError):
        return False


def main() -> None:
    ap = argparse.ArgumentParser(description="Remove CLI wrapper")
    ap.add_argument("--cli", required=True, help="CLI name to unwrap")
    ap.add_argument(
        "--dir",
        type=Path,
        default=DEFAULT_DIR,
        help=f"Directory where wrapper is installed (default: {DEFAULT_DIR})",
    )
    ap.add_argument("--dry-run", action="store_true", help="Print actions without removing")
    args = ap.parse_args()

    wrapper_path = args.dir.expanduser() / args.cli

    if not wrapper_path.exists():
        print(f"Not found: {wrapper_path}")
        return

    if not is_our_wrapper(wrapper_path):
        print(f"Warning: {wrapper_path} is not a wrapper generated by ai-hooks-integration")
        print("Skipping removal for safety")
        return

    if args.dry_run:
        print(f"[dry-run] remove {wrapper_path}")
        return

    wrapper_path.unlink()
    print(f"Removed: {wrapper_path}")


if __name__ == "__main__":
    main()
